version: '3.8'

services:
  # PostgreSQL 서비스
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123!
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    networks:
      - hive_network

  # Hive Metastore 서비스
  metastore:
    image: apache/hive:3.1.3
    container_name: metastore-standalone
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive123!"
    ports:
      - "9083:9083"
    depends_on:
      - postgres  # PostgreSQL 서비스가 먼저 실행되어야 Hive Metastore가 실행됨
    networks:
      - hive_network

networks:
  hive_network:
    driver: bridge
