/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.scala-lang:scala-library:2.13.15")

    // Spark 추가
    implementation("org.apache.spark:spark-core_2.13:3.5.3")
    implementation("org.apache.spark:spark-sql_2.13:3.5.3")

    // Hive 추가
    implementation("org.apache.spark:spark-hive_2.13:3.5.3")
    implementation("org.postgresql:postgresql:42.2.5")

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    // testImplementation(libs.scalatest.v2.v13)
    // testImplementation(libs.junit.v4.v13.v2.v13)

    // Need scala-xml at test runtime
    // testRuntimeOnly(libs.scala.xml.v2.v13)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
