/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example
import com.example.config.ConfigUtils
import com.example.spark.LogProcessor
import org.apache.spark.sql.SparkSession

object App {
  def main(args: Array[String]): Unit = {
    // 설정 파일 로딩
    val config = ConfigUtils.loadFromProperties("conf/conf.properties")

    val spark = SparkSession.builder()
      .appName("LogProcessor")
      .config("spark.sql.shuffle.partitions", "2")
      .config("spark.driver.bindAddress", "127.0.0.1")
      .master("local[*]")
      .enableHiveSupport()
      .getOrCreate()

    val processor = new LogProcessor(spark)
    processor.process(config)

    spark.stop()
  }

}
